
version: 2


sources:
  - name: Snowflake_sample_data
    description: 'sample database'
    database: Snowflake_sample_data
    schema: tpcds_sf10tcl
    tables:
      - name: item
        description: 'item table'
      - name: store
        description: 'store table'

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
